name: Lint and Test

on:
  push:
    branches: main
  pull_request:

jobs:
  lint-and-test:
    strategy:
      matrix:
        runner: [macos-13, ubuntu-latest, windows-latest]
        rust-version: ["1.72"]

    runs-on: "${{matrix.runner}}"

    steps:
      # TODO: Consider adding caching.
      - name: Setup Rust
        run: |
          rustup default "${{matrix.rust-version}}"
          rustup component add rustfmt clippy
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Check formatting
        run: cargo fmt --check
      - name: Run linter
        run: cargo clippy
      - name: Run tests
        run: cargo test
