name: Publish Binary Framework

on:
  workflow_dispatch: # trigger manually
    inputs:
      version:
        description: 'Version to publish.'
        type: string
        required: true

env:
  rust_version: "1.72"

# TODO: Lint/format/test Rust code in separate build script.

jobs:
  build_publish:
    runs-on: macos-13

    steps:
      - name: Setup Rust
        run: |
          rustup default "${{env.rust_version}}"
          rustup target install \
            aarch64-apple-darwin \
            aarch64-apple-ios \
            aarch64-apple-ios-sim \
            x86_64-apple-darwin \
            x86_64-apple-ios
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build binary framework
        run: ./build.sh # produces './generated/RustFramework.xcframework'
      - name: Archive framework
        working-directory: ./generated
        run: |
          zip -r ./RustFramework.xcframework.zip ./RustFramework.xcframework
          swift package compute-checksum ./RustFramework.xcframework.zip > ./CHECKSUM
      - name: Upload package as GitHub release
        uses: softprops/action-gh-release@v1
        with:
            files: |
              ./generated/RustFramework.xcframework.zip
              ./generated/CHECKSUM
            name: '${{github.event.inputs.version}}'
            generate_release_notes: true
