name: Publish Binary Framework

on:
  workflow_dispatch: # trigger manually
    inputs:
      version:
        description: 'Version to publish.'
        type: string
        required: true

env:
  rust_version: '1.72'

jobs:
  build_publish:
    runs-on: macos-latest

    steps:
    - name: Check out sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Rust
      run: make setup
    - name: Build binary framework
      run: make framework # produces './generated/ConcordiumWalletCryptoUniffi.xcframework'
    - name: Archive framework
      working-directory: ./generated
      run: |
        ditto -c -k --sequesterRsrc --keepParent ./ConcordiumWalletCryptoUniffi.xcframework ./ConcordiumWalletCryptoUniffi.xcframework.zip
        swift package compute-checksum ./ConcordiumWalletCryptoUniffi.xcframework.zip > ./CHECKSUM
    - name: Upload package as GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./generated/ConcordiumWalletCryptoUniffi.xcframework.zip
          ./generated/CHECKSUM
        name: '${{github.event.inputs.version}} (framework)'
        generate_release_notes: true
